### ISSUE TITLE
NPE (ServiceLocaterUtilities) when commenting MR

### ISSUE THREAD

**Issue by noidic** [jenkinsci/violation-comments-to-gitlab-plugin#26]
Jenkins: 2.2.0
Gitlab: 12.7.5
Plugin: 2.3.9

Pipeline:
`
step([

	$class: 'ViolationsToGitLabRecorder',

	config: [

			apiTokenCredentialsId                         : 'GitlabCI',

			apiTokenPrivate                               : true,

			authMethodHeader                              : true,

			commentOnlyChangedContent                     : false,

			commentOnlyChangedFiles                       : true,

			commentTemplate                               : '**Severity**: {{violation.severity}}<br>**Source**: <i>{{violation.file}}:{{violation.endLine}}</i><br>{{violation.message}}',

			createSingleFileComments                      : true,

			gitLabUrl                                     : 'http://git/',

			ignoreCertificateErrors                       : true,

			keepOldComments                               : true,

			mergeRequestIid                               : env.gitlabMergeRequestIid,

			minSeverity                                   : 'INFO',

			maxNumberOfViolations                         : 9999,

			createCommentWithAllSingleFileComments        : true,

			shouldSetWip                                  : false,

			projectId                                     : env.gitlabMergeRequestTargetProjectId,

			enableLogging                                 : true,

			violationConfigs                              : [

					[parser: 'SONAR', pattern: '.*/sonar/report.*json', reporter: 'Sonar'],

					[parser: 'JUNIT', pattern: '.*/surefire-reports/.*xml', reporter: 'JUnit']

			]

	]])
`

StackTrace:
`java.lang.RuntimeException: Could not get project 1249
	at se.bjurr.violations.comments.gitlab.lib.GitLabCommentsProvider.<init>(GitLabCommentsProvider.java:72)
	at se.bjurr.violations.comments.gitlab.lib.ViolationCommentsToGitLabApi.toPullRequest(ViolationCommentsToGitLabApi.java:175)
	at org.jenkinsci.plugins.jvctgl.perform.JvctglPerformer.doPerform(JvctglPerformer.java:160)
	at org.jenkinsci.plugins.jvctgl.perform.JvctglPerformer$2.invoke(JvctglPerformer.java:268)
	at org.jenkinsci.plugins.jvctgl.perform.JvctglPerformer$2.invoke(JvctglPerformer.java:256)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3069)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Caused by: org.gitlab4j.api.GitLabApiException
	at org.gitlab4j.api.AbstractApi.handle(AbstractApi.java:604)
	at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:182)
	at org.gitlab4j.api.ProjectApi.getProject(ProjectApi.java:665)
	at se.bjurr.violations.comments.gitlab.lib.GitLabCommentsProvider.<init>(GitLabCommentsProvider.java:70)
	... 13 more

Caused by: java.lang.NullPointerException
	at org.glassfish.hk2.utilities.ServiceLocatorUtilities.addClasses(ServiceLocatorUtilities.java:411)
	at org.glassfish.hk2.utilities.ServiceLocatorUtilities.enablePerThreadScope(ServiceLocatorUtilities.java:83)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.createLocator(AbstractHk2InjectionManager.java:92)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.<init>(AbstractHk2InjectionManager.java:62)
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.<init>(ImmediateHk2InjectionManager.java:38)
	at org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory$Hk2InjectionManagerStrategy$1.createInjectionManager(Hk2InjectionManagerFactory.java:55)
	at org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory.create(Hk2InjectionManagerFactory.java:73)
	at org.glassfish.jersey.internal.inject.InjectionManagerFactory.create(InjectionManagerFactory.java:32)
	at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:44)
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:408)
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317)
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:802)
	at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:261)
	at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:119)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:88)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:84)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:75)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:395)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:295)
	at org.gitlab4j.api.GitLabApiClient.get(GitLabApiClient.java:384)
	at org.gitlab4j.api.GitLabApiClient.get(GitLabApiClient.java:372)
	at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:180)
	... 15 more`

**Comment by tomasbjerre** [comment]
Looks like a crash in gitlab4j.
Do you see anything else logged before this? Any request/response?

**Comment by noidic** [comment]
No, neither in Jenkins nor gitlab logs. As a side node, setting the build status works fine.

I started another build on the same code and the same slave. This time, no error is reported but the plugin just stops after printing out the merge request id. For comparison:

Build with exception:
```
Running Violation Comments To GitLab
Merge request: 121
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage

[Pipeline] { (Declarative: Post Actions)

[Pipeline] updateGitlabCommitStatus

Workspace: /usr/jenkins/workspace/CAZ2-library-eworks-basis-2-mr/sourceBranch
Found 4485 violations from ViolationConfig [pattern=.*/sonar/report.*json, parser=SONAR, reporter=Sonar].
Found 0 violations from ViolationConfig [pattern=.*/surefire-reports/.*xml, parser=JUNIT, reporter=JUnit].
Will comment PR http://git/ 1249 121
java.lang.RuntimeException: Could not get project 1249
	at se.bjurr.violations.comments.gitlab.lib.GitLabCommentsProvider.<init>(GitLabCommentsProvider.java:72)`

Build without:
`Running Violation Comments To GitLab
Merge request: 121
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage

[Pipeline] { (Declarative: Post Actions)

[Pipeline] updateGitlabCommitStatus

[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```

Neither build does any commenting on the MR.

**Comment by noidic** [comment]
I checked other builds, every time it is either the exception or the plugin stopping after printing the merge request id, not a single one posted a comment in gitlab.

**Comment by tomasbjerre** [comment]
You should always use an LTS version of Jenkins:
https://jenkins.io/changelog-stable/

And your version is very old!

Also, what Java version are you running Jenkins on?

**Comment by noidic** [comment]
Sorry, Jenkins Version is 2.220, not 2.2.0. Jenkins ist running on OpenJDK 1.8.0_242-b08

**Comment by nekator** [comment]
Error happens on OpenJDK 11.0.6+10-LTS and probably other distributions of JDK 11. All Java 1.8 Versions work fine.

**Comment by tomasbjerre** [comment]
I just made a new release (2.40) with latest version of the client:
https://github.com/gitlab4j/gitlab4j-api

Perhaps that fixes it, or else this should probably be an issue on that library.

**Comment by squalou** [comment]
Hi,
I'm facing the same issue with
- plugin 2.43
- jenkins 2.235.2
- jdk of jenkins master : 1.8.252
- jdk of agent where the build is done : 11.0.8
- gitlab 12.8.6

Builds done on jdk 8 work fine, (I can switch a test project from 8 to 11 easily, 11 fails everytime with above NPE) :



```
 java.lang.RuntimeException: Could not get project   aaa/bbbb
at se.bjurr.violations.comments.gitlab.lib.GitLabCommentsProvider.<init>(GitLabCommentsProvider.java:73)
...
...
Caused by: org.gitlab4j.api.GitLabApiException
at org.gitlab4j.api.AbstractApi.handle(AbstractApi.java:655)
...
 Caused by: java.lang.NullPointerException
at org.glassfish.hk2.utilities.ServiceLocatorUtilities.addClasses(ServiceLocatorUtilities.java:411)
```

**Comment by tomasbjerre** [comment]
You may try the command line tool:
https://www.npmjs.com/package/violation-comments-to-gitlab-command-line

Difference would be that it has its own classpath, not shared with Jenkins. If that also crashes same way I would say it is a bug in the lib:
https://github.com/gitlab4j/gitlab4j-api/issues/523

**Comment by squalou** [comment]
I'm trying.
I mean : I have to work locally for this, no npm available on my jenkins infra.

I set my JAVA_HOME to jdk11, do I have to do anything else ? I'm not fluent in node ecosystem.

Command works without errors, it outputs communication with gitlab successfully.

Here's what I do
- mvn sonar:sonar (with lot of properties relative to sonar)
- violation-comments-to-gitlab-command-line -api-token xxxxxxxxxxx -api-token-private true -gitlab-url 'https://gitlab.mydomain.com' -mr-iid 3 -pi 'group/myproject' --violations 'SONAR' '/home/somewhere/project/target/sonar/sonar-report.json' ".*json$" 'Sonar'

Output look sfine


For instance
```
INFO Sonar INFO squid:UselessImportCheck src/main/xxxxxxxxxxxxxxxxxxxxxxxxxxx/somefile.java 10 com.package.platform:project:src/main/jxxxxxxxxxxxxxxxxx/somefile.java
INFO 34 - Sending client request on thread main
34 > POST https://gitlab.mydomain.com/api/v4/projects/268/merge_requests/3/discussions
34 > Accept: application/json
34 > Content-Type: application/x-www-form-urlencoded
34 > PRIVATE-TOKEN: ********

INFO 34 - Received server response on thread main
34 < 201
34 < Cache-Control: max-age=0, private, must-revalidate
34 < Connection: keep-alive
34 < Content-Length: 1498
34 < Content-Type: application/json
34 < Date: Fri, 18 Sep 2020 09:48:47 GMT
34 < Etag: W/"229906d8c89f61ef3434a2d5fe7a656d"
34 < Referrer-Policy: strict-origin-when-cross-origin
34 < Server: nginx
34 < Strict-Transport-Security: max-age=31536000
34 < Vary: Origin
34 < X-Content-Type-Options: nosniff
34 < X-Frame-Options: SAMEORIGIN
34 < X-Request-Id: d58TDt4vwu5
34 < X-Runtime: 0.
```

And MR is well commented.

I may be missing something with node and jdk settings, please tell me if I need to check anything

**Comment by tomasbjerre** [comment]
The npm-package is just for distribution. If you do not have Node, you can get the `violation-comments-to-gitlab-command-line` package in version `1.17` from JCenter in Bintray:
https://bintray.com/tomasbjerre/tomasbjerre/se.bjurr.violations%3Aviolation-comments-to-gitlab-command-line/_latestVersion
Or Central (search.maven.com).

And run thar jar with `java -jar violation-comments-to-gitlab-command-line-1.17.jar`

**Comment by squalou** [comment]
Great, thank you.
I've just re-run my tests, using the jar : it works fine.

More detailed info : 

```
$ java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10)
OpenJDK 64-Bit Server VM (build 11.0.8+10, mixed mode)

```

command run
```
java -jar ~/Downloads/violation-comments-to-gitlab-command-line-1.17.jar -api-token xxxxxxxxxxxxxxxxxx -api-token-private true -gitlab-url 'https://gitlab.mydomain.com' -mr-iid 3 -pi 'group/project' --violations 'SONAR' '/home/project/target/sonar/sonar-report.json' ".*json$" 'Sonar'
```


for instance with a violation that disappeared : 

```

INFO Asking GitLabCommentsProvider to comment:
INFO 5 - Sending client request on thread main
5 > DELETE https://gitlab.mydomain.com/api/v4/projects/268/merge_requests/3/notes/50338
5 > Accept: application/json
5 > PRIVATE-TOKEN: ********

INFO 5 - Received server response on thread main
5 < 204
5 < Cache-Control: no-cache
5 < Connection: keep-alive
5 < Date: Fri, 18 Sep 2020 12:38:49 GMT
5 < Referrer-Policy: strict-origin-when-cross-origin
5 < Server: nginx
5 < Strict-Transport-Security: max-age=31536000
5 < Vary: Origin
5 < X-Content-Type-Options: nosniff
5 < X-Frame-Options: SAMEORIGIN
5 < X-Request-Id: U3zqs0DoBW
5 < X-Runtime: 0.034687

```

the only difference I can think of is that my jenkins uses Alpine based docker image, can't see why it would change anything, will give it a try to confirm.

**Comment by squalou** [comment]
Checked with the docker image used on production system : it also works when running the java -jar command.

(note : it may provide an ugly workaround by the way ;-) )

**Comment by squalou** [comment]
Summary : I can confirm
- plugin fails when used from a jenkins agent running jdk11
- but using .jar command line it works fine (from the very same execution context)

I have my workaround .. now good luck to try to fix the plugin. 
I'll be happy to help by any mean if I can

thanks again for your support !
